config/routes.rb
Rails.application.routes.draw do
  #----------------------------------Home & General Routes --------------------------------------------#
  root to: 'home#index'
  get 'home/index'

  resources :articles do
    resources :comments
  end

  resources :users
  #----------------------------------Article Routes -----------------------------------------#
  get 'articles', to: 'articles#index'
  get 'articles/new', to: 'articles#new'
  get 'articles/:id', to: 'articles#show'
  get 'articles/:id/edit', to: 'articles#edit'
  post 'articles', to: 'articles#create'
  delete 'articles/:id', to: 'articles#destroy'

  #----------------------------------Comment Routes -----------------------------------------#
  get 'comments', to: 'comments#index'
  get 'comments/new', to: 'articles#new'
  post '/articles/:id/comments', to: 'comments#create'
  delete '/articles/:id/comments/:id', to: 'comments#destroy'

  #----------------------------------User Routes -----------------------------------------#

  get 'users', to: 'users#index'
  get 'sendToken', to: 'users#sendToken'
  delete 'users/:id', to: 'users#destroy'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :imagen
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  alias_attribute :password_digest, :clave_digest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Response

  helper_method :logged_in?
  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  skip_before_action :verify_authenticity_token
  #Find the article for show, edit, update and destroy actions (%i means array with withespaces)
  before_action :set_article, only: %i[ show edit update destroy]

  # GET /articles ; /articles.json
  def index
    @articles = Article.all
    json_response(@articles)
  end

  # GET /articles/id ; /articles/id.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new

  end

  # POST /articles ; /articles.json
  def create
    @article = Article.new(article_params)
    @article.id = Article.maximum("id")+1

    if @article.save
      if current_user.tipo == "1"
        redirect_to '/client/admin_content_panel.html'
      else
        redirect_to '/client/writer_content_panel.html'
      end
    else
      render 'new'
    end
  end

  # GET /articles/id/edit
  def edit
  end

  # PATCH/PUT /articles/id ; /articles/id.json
  def update
    if @article.update(article_params)
      if current_user.tipo == "1"
        redirect_to '/client/admin_content_panel.html'
      else
        redirect_to '/client/writer_content_panel.html'
      end
    else
      render 'edit'
    end
  end

  # DELETE /articles/id ; /articles/id.json
  def destroy
    @article.destroy
    redirect_to articles_path
  end


  #Aux Methods
  private

  #Sets an article for show, edit, update and destroy actions
  def set_article
    @article = Article.find(params[:id])
  end

  #Sets the allowed article parameters
  def article_params
    params.require(:article).permit(:user_id, :foto, :fecha, :titulo, :subtitulo, :seccion, :cuerpo, :imagen)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  skip_before_action :verify_authenticity_token

  # GET /comments ; /comments.json
  def index
    @comments = Comment.all
    json_response(@comments)
  end

  # POST /articles/id/comments
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  # GET /articles/id/comments/id/edit
  def edit
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end


  def update
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if @comment.update(comment_params)
        redirect_to '/client/admin_comments_panel.html'
    else
      render 'edit'
    end
  end

  #DELETE /articles/id/comments/id ; /articles/id/comments/id.json
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit( :user_id, :article_id, :texto)
  end

end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    if logged_in?
      redirect_to '/client/home_registered.html'
    else
      redirect_to '/client/home.html'
    end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :verify_authenticity_token
  def welcome
  end

  def new
  end

  def create
    @user = User.find_by(nombre: params[:nombre])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      #redirect_to user_path(@user)
      redirect_to "/client/home_registered.html"
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.clear
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :verify_authenticity_token
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users ; /users.json
  def index
    @users = User.all
    json_response(@users)
  end


  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users ; /users.json
  def create
    @user = User.new(user_params)
    @user.id = User.maximum("id")+1
    if @user.save
      session[:user_id] = @user.id
      #redirect_to user_path(@user)
      redirect_to "/client/profile.html"
    else
      render :new
    end
  end



  # GET /users/id ; /users/id.json
  def show
  end

  # GET /users/id/edit
  def edit
    if !logged_in? || !@user
      redirect_to root_path
    end
  end

  # PATCH/PUT /users/id ; /users/id.json
  def update
    if @user
      @user.update(user_params)

      if @user.errors.any?
        render "edit"
      else
        redirect_to "/client/profile.html"
      end
    else
      render "edit"
    end
  end

  # DELETE /users/id ; /users/id.json
  def destroy
    if current_user.id != @user.id
      @user.destroy
    end
  end

  # GET /sendToken
  def sendToken
    @user = current_user
    json_response(@user)
  end

  private

  def user_params

    params.require(:user).permit(:foto, :nombre, :apellidos, :email, :password, :tipo)
  end

  def set_user
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.hidden_field :fecha, :value => Time.now.to_i %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :subtitulo %>
    <%= form.text_field :subtitulo %>
  </div>

  <div class="field">
    <%= form.label :seccion %>
    <%= form.select(:seccion, ['Futbol', 'Baloncesto', 'Tenis', 'Ciclismo', 'Motor', 'eSports'] )%>
  </div>

  <div class="field">
    <%= form.label :imagen%>
    <%= form.file_field :imagen %>
  </div>

  <div class="field">
    <%= form.label :cuerpo %>
    <%= form.text_area :cuerpo, :cols => 70, :rows => 10 %>
  </div>

  <%= form.hidden_field :user_id, :value => current_user.id %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editar Articulo</h1>
<%= render 'form', article: @article %>
<%= link_to 'Show', @article %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Noticias</h1>
<table>
  <tr>
    <th>Foto</th>
    <th>Fecha</th>
    <th>Titulo</th>
    <th>Subtitulo</th>
    <th>Seccion</th>
    <th>Cuerpo</th>
  </tr>

  <tbody>
    <% @articles.each do |i| %>
      <tr>
        <td><%= i.foto %></td>
        <td><%= i.fecha %></td>
        <td><%= i.titulo %></td>
        <td><%= i.subtitulo %></td>
        <td><%= i.seccion %></td>
        <td><%= i.cuerpo %></td>
        <td><%= link_to 'Ir a la noticia', i %></td>
        <td><%= link_to 'Editar', edit_article_path(i) %></td>
        <td><%= link_to 'Eliminar', i, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Nueva Noticia', 'articles/new' %>

app/views/articles/new.html.erb
<h1>Crear una Noticia</h1>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1> Artículo: <%= @article.titulo %></h1>

<p>
  <strong>Foto:</strong>
  <%= @article.foto %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @article.fecha %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @article.titulo %>
</p>

<p>
  <strong>Subtitulo:</strong>
  <%= @article.subtitulo %>
</p>

<p>
  <strong>Seccion:</strong>
  <%= @article.seccion %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @article.cuerpo %>
</p>


<h2>Comentarios</h2>
<%= render @article.comments %>

<h2> Añadir comentario</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path%>

app/views/comments/_comment.html.erb
<p>
  <strong>Autor:</strong>
  <%= comment.user.nombre%>
</p>
<p>
  <strong>Comentario:</strong>
  <%= comment.texto %>
</p>

<p>
  <%= link_to 'Eliminar Comentario',
              [comment.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @comment ], local: true) do |form| %>
  <div>
    <%= form.hidden_field :user_id, value: @comment.user_id %>
  </div>

  <div class="field">
    <%= form.label :texto %><br>
    <%= form.text_area :texto, :cols => 80, :rows => 20 %>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>


<% end %>

app/views/comments/edit.html.erb
<h1>Editar Comentario</h1>

<%= render 'form', comment: @comment %>

app/views/comments/index.html.erb
<h1 >Comentarios</h1>
<table>
  <tr>
    <th>Autor</th>
    <th>Comentario</th>
    <th>Noticia</th>
    <th>Acciones</th>
  </tr>

  <tbody>
  <% @comments.each do |i| %>
    <tr>
      <td><%= i.user.nombre %></td>
      <td><%= i.texto %></td>
      <td><%= i.article.titulo %></td>
      <td><%= link_to 'Ir a la noticia del comentario', i.article %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1>Planeta Deporte</h1>
<%= link_to 'Noticias', articles_path %>
<%= link_to 'Comentarios', comments_path %>

app/views/layouts/_nav.html.erb
<% if !logged_in? %>

  <%= link_to image_tag("logo.png", :alt=>"logo", :class=>"Logo"), root_path %>
  <%= link_to "Fútbol", '/client/sport_section.html?seccion=futbol'%>
  <%= link_to "Baloncesto", '/client/sport_section.html?seccion=baloncesto' %>
  <%= link_to "Tenis", '/client/sport_section.html?seccion=tenis' %>
  <%= link_to "Motor", '/client/sport_section.html?seccion=motor' %>
  <%= link_to "eSport", '/client/sport_section.html?seccion=esports' %>
  <%= link_to "Iniciar Sesion", login_path %>
  <%= link_to "Registrarse", new_user_path %>
<% else %>
  <%= link_to image_tag("logo.png", :alt=>"logo", :class=>"Logo"), '/client/home_registered.html'%>
  <%= link_to "Fútbol", '/client/sport_section_registered.html?seccion=futbol'%>
  <%= link_to "Baloncesto", '/client/sport_section_registered.html?seccion=baloncesto' %>
  <%= link_to "Tenis", '/client/sport_section_registered.html?seccion=tenis' %>
  <%= link_to "Motor", '/client/sport_section_registered.html?seccion=motor' %>
  <%= link_to "eSport", '/client/sport_section_registered.html?seccion=esports' %>
  <%= link_to "Cerrar Sesion", logout_path, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanetaDeporteRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Editar mis datos</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= f.label :nombre %><br>
  <%= f.text_field :nombre, autofocus: true %><br>

  <%= f.label :apellidos %><br>
  <%= f.text_field :apellidos%><br>

  <%= f.label :email %><br>
  <%= f.text_field :email%><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.submit "Confirm Changes" %>
<% end %>

app/views/users/new.html.erb
<% if logged_in? && current_user.tipo == "1" %>
    <h1>Crear Usuario</h1>

<% else %>

  <h1>Registrarse</h1>
<% end %>


<%= form_with model: @user, local: true do |f| %>
  <%= f.label :nombre %><br>
  <%= f.text_field :nombre %><br><br>

  <%= f.label :apellidos %><br>
  <%= f.text_field :apellidos %><br><br>

  <%= f.label :email %><br>
  <%= f.text_field :email %><br><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br><br>


  <% if logged_in? && current_user.tipo == "1" %>
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %><br><br>
    <%= f.submit "Crear usuario" %>
  <% else %>

    <%= f.hidden_field :tipo, :value => "3" %>
    <%= f.submit "Registrarse" %>

  <% end %>


<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.nombre %></h1>
<%= link_to "Edit Account", edit_user_path(current_user) %>
<%= link_to "Delete Account", current_user, data: { confirm: "Are you sure?" }, method: :delete %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>